version: "3.8"
services:
  main:
    container_name: ${COMPOSE_PROJECT_NAME}_main
    build:
      context: .
      dockerfile: Dockerfile
    image: ${COMPOSE_PROJECT_NAME}:latest
    restart: always
    env_file:
      - .env.local
    environment:
      # - DATABASE_URL=${DATABASE_URL_DOCKER}
      - PORT=${PORT}
    ports:
      - "${PORT}:3000"
    # depends_on:
    #   - postgres
    entrypoint: ["npm", "start"]
    # networks:
    #   - ${COMPOSE_PROJECT_NAME}

#   postgres:
#     container_name: ${COMPOSE_PROJECT_NAME}_postgres
#     image: postgres:latest
#     restart: always
#     ports:
#       - "127.0.0.1:5434:5432"  # Cambia el puerto de 5433 a 5434
#     volumes:
#       - pgdata:/var/lib/postgresql/data/
#       - ./dump/init.dump.sql:/docker-entrypoint-initdb.d/init.dump.sql
#     environment:
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_DB=${POSTGRES_DB}
#       - POSTGRES_HOST_AUTH_METHOD=trust
#     networks:
#       - ${COMPOSE_PROJECT_NAME}

# volumes:
#   pgdata:
#     driver: local

# networks:
#   ${COMPOSE_PROJECT_NAME}:
#     driver: bridge
